<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CoursesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('courses')->truncate();
        DB::table('courses')->insert([
            array('id' => '1', 'code' => 'SSP00000001C0000001', 'institute_id' => '1', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '2', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'কম্পিউটার বেসিক এ্যান্ড আইসিটি এপ্লিকেশন', 'title_en' => 'Computer Basic and ICT Applications', 'course_fee' => '1000.00', 'duration' => '360.00', 'overview' => '৬ মাস', 'overview_en' => '6 month', 'target_group' => 'বেকার যুব ও যুব মহিলা', 'target_group_en' => 'Unemployed youth and young women', 'objectives' => 'কর্মসংস্থানের সুযোগ সৃস্টি করা', 'objectives_en' => 'Creating employment opportunities', 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => 'সরাসরি ও অনলাইনের মাধ্যমে', 'training_methodology_en' => 'Directly and online', 'evaluation_system' => 'সরাসরি লিখিত ও ব্যবহারিক পরীক্ষা', 'evaluation_system_en' => 'Direct written and practical examination', 'prerequisite' => 'বয়স সীমা ১৮-৩৫ বছরের মধ্যে এবং বাংলাদেশের স্থায়ী নাগরিক', 'prerequisite_en' => 'Age range between 18-35 years and permanent citizen of Bangladesh', 'eligibility' => 'এইচ,এস,সি পাশ বা সমমানের পরীক্ষায় উত্তীর্ণ', 'eligibility_en' => 'H, S, C pass or equivalent examination', 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/MADBrqySsFwQVkK767zc6FRVJLx66l1647075755.jpg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[true,true],\\"freedom_fighter_info\\":[true,true],\\"disability_info\\":[true,true],\\"education_info\\":[true,true],\\"psc_passing_info\\":[false,false],\\"jsc_passing_info\\":[false,false],\\"ssc_passing_info\\":[true,true],\\"hsc_passing_info\\":[true,true],\\"diploma_passing_info\\":[false,false],\\"honors_passing_info\\":[false,false],\\"masters_passing_info\\":[true,true],\\"phd_passing_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[true,true],\\"miscellaneous_info\\":[true,true]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-02 02:13:50', 'updated_at' => '2022-03-12 21:02:37', 'deleted_at' => NULL),
            array('id' => '6', 'code' => 'SSP00000004C0000001', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'আমিনশিপ', 'title_en' => 'Aminship', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/mvznftYFCRHYDRznNnHkB8e3AmQTeo1646553384.jpg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 19:56:27', 'updated_at' => '2022-03-06 22:47:03', 'deleted_at' => NULL),
            array('id' => '8', 'code' => 'SSP00000004C0000002', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'সার্টিফিকেট ইন বিউটিফিকেশন', 'title_en' => 'CERTIFICATE IN BEAUTIFICATION', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/BCQgKDvTunZjJtlLVWJpQhnqJ8lAC91646553555.jpg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 20:02:49', 'updated_at' => '2022-03-06 20:02:49', 'deleted_at' => NULL),
            array('id' => '10', 'code' => 'SSP00000004C0000003', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'কম্পিউটার অফিস অ্যাপ্লিকেশন', 'title_en' => 'COMPUTER OFFICE APPLICATION', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/GWn8rlTc0HaWemzxYgZ8qWHU2ZOd551646553904.jpg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 20:05:12', 'updated_at' => '2022-03-06 20:05:12', 'deleted_at' => NULL),
            array('id' => '12', 'code' => 'SSP00000004C0000004', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'ইলেকট্রিকাল হাউস ওয়েরিং', 'title_en' => 'Electrical House wearing', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/CHtGRkqLk6SrfMoRM59310N9qRTvGk1646557897.jpg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 21:13:07', 'updated_at' => '2022-03-06 21:19:08', 'deleted_at' => NULL),
            array('id' => '15', 'code' => 'SSP00000004C0000005', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'গ্রাফিক্স ডিজাইন', 'title_en' => 'Graphics design', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/RAV6FDc2WfIyG52OIcTyWZtr6QEcgK1646558427.jfif', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 21:15:31', 'updated_at' => '2022-03-06 21:20:34', 'deleted_at' => NULL),
            array('id' => '18', 'code' => 'SSP00000004C0000006', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'হার্ডওয়্যার', 'title_en' => 'Hardware', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/XT3FinT4Z5B9DfpSNQN24v8M54Pbfs1646558456.jfif', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 21:22:09', 'updated_at' => '2022-03-06 21:22:09', 'deleted_at' => NULL),
            array('id' => '19', 'code' => 'SSP00000004C0000007', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'মোবাইল সার্ভিসিং', 'title_en' => 'mobile Servicing', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/BqyLVfuJQjdybO2lZZ5GmOJOJUal6z1646558580.jfif', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 21:24:30', 'updated_at' => '2022-03-06 21:24:30', 'deleted_at' => NULL),
            array('id' => '21', 'code' => 'SSP00000004C0000008', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'অফিস অ্যাপ্লিকেশান', 'title_en' => 'Office Application', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/O06loLcT8Kk1ojK2IX0cofD20mobpx1646558684.jpg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 21:25:52', 'updated_at' => '2022-03-06 21:25:52', 'deleted_at' => NULL),
            array('id' => '24', 'code' => 'SSP00000004C0000009', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'ল্যাংগুয়েজ প্রফিসিয়েন্সি', 'title_en' => 'Language Proficiency', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/LX9v66P5HIQFRMRHZNscl7o7KNA9XK1646558765.jfif', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 21:27:43', 'updated_at' => '2022-03-06 21:27:43', 'deleted_at' => NULL),
            array('id' => '27', 'code' => 'SSP00000004C0000010', 'institute_id' => '6', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'রেফ্রিজারেটর এন্ড এয়ার কন্ডিশনার', 'title_en' => 'Refrigerator and Air conditioner', 'course_fee' => '2400.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/2DeuYaRyFvNzNsz57p5Jlxyx8yImAN1646558875.jfif', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-06 21:29:26', 'updated_at' => '2022-03-06 21:29:26', 'deleted_at' => NULL),
            array('id' => '29', 'code' => 'SSP00000012C0000001', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'Graphics design', 'title_en' => 'Graphics design', 'course_fee' => '3700.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/xZGRTCAv9I2IyzQl6SALBesO8v69Ev1646712619.jpeg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 16:10:22', 'updated_at' => '2022-03-08 16:10:22', 'deleted_at' => NULL),
            array('id' => '30', 'code' => 'SSP00000012C0000002', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'Auto-CAD 2D 3D', 'title_en' => 'Auto-CAD 2D 3D', 'course_fee' => '5175.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/882YMRStDEdjt8CubFVX4rcNsSsJyj1646712912.webp', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 16:15:17', 'updated_at' => '2022-03-08 16:15:17', 'deleted_at' => NULL),
            array('id' => '31', 'code' => 'SSP00000012C0000003', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'CBT& A Methodology', 'title_en' => 'CBT& A Methodology', 'course_fee' => '2500.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/XfBAusE6cg6tF6PH7aJALYx6snPeAC1646713051.png', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 16:17:47', 'updated_at' => '2022-03-08 16:17:47', 'deleted_at' => NULL),
            array('id' => '32', 'code' => 'SSP00000012C0000004', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'Graphic design occupation', 'title_en' => 'Graphic design occupation', 'course_fee' => '2500.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/OEHGjvkIg1SGCfKn9W2lPmhxzGNCCZ1646713255.jpeg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 16:21:04', 'updated_at' => '2022-03-08 16:21:04', 'deleted_at' => NULL),
            array('id' => '35', 'code' => 'SSP00000012C0000005', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'Tally.ERP-9 (Accounting Software)', 'title_en' => 'Tally.ERP-9 (Accounting Software)', 'course_fee' => '4500.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/Sqkz74U3iEY6PD685OyjD8c7WaSWcO1646714144.jfif', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 16:35:48', 'updated_at' => '2022-03-08 16:35:48', 'deleted_at' => NULL),
            array('id' => '38', 'code' => 'SSP00000012C0000006', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'Web Development', 'title_en' => 'Web Development', 'course_fee' => '4500.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/wnsVmlP1CkB69wfEyyrH7T4an4wrpG1646715005.JPG', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 16:50:08', 'updated_at' => '2022-03-08 16:50:08', 'deleted_at' => NULL),
            array('id' => '41', 'code' => 'SSP00000012C0000007', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'Teaching learning management', 'title_en' => 'Teaching learning management', 'course_fee' => '10000.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/n3vGalCWRpGzYuQ29kNGt10yLvRSEn1646715128.jpeg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 16:52:12', 'updated_at' => '2022-03-08 16:52:12', 'deleted_at' => NULL),
            array('id' => '42', 'code' => 'SSP00000012C0000008', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'Cyber security', 'title_en' => 'Cyber security', 'course_fee' => '10000.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/YN6pInPm7iIs9HiKGnOARrsiqM5uic1646715240.jfif', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 16:54:04', 'updated_at' => '2022-03-08 16:54:04', 'deleted_at' => NULL),
            array('id' => '43', 'code' => 'SSP00000012C0000009', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'Construction and engineering site management', 'title_en' => 'Construction and engineering site management', 'course_fee' => '10000.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/EJfqSn9DFj0XnBONrDUzengmaw9muP1646715383.jfif', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 16:56:26', 'updated_at' => '2022-03-08 16:56:26', 'deleted_at' => NULL),
            array('id' => '44', 'code' => 'SSP00000012C0000010', 'institute_id' => '20', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'Public procurement', 'title_en' => 'Public procurement Act-2006, Rules-2008 & E-Tendaring', 'course_fee' => '10000.00', 'duration' => NULL, 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => NULL, 'objectives_en' => NULL, 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => NULL, 'training_methodology_en' => NULL, 'evaluation_system' => NULL, 'evaluation_system_en' => NULL, 'prerequisite' => NULL, 'prerequisite_en' => NULL, 'eligibility' => NULL, 'eligibility_en' => NULL, 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/LdZgBQf3By0QrX9nLnLdrvidNcHQpR1646715611.webp', 'application_form_settings' => '"{\\"ethnic_group_info\\":[false,false],\\"freedom_fighter_info\\":[false,false],\\"disability_info\\":[false,false],\\"education_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[false,false],\\"miscellaneous_info\\":[false,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-08 17:00:16', 'updated_at' => '2022-03-08 17:00:16', 'deleted_at' => NULL),
            array('id' => '47', 'code' => 'SSP00000001C0000002', 'institute_id' => '1', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'পোষাক তৈরী প্রশিক্ষণ', 'title_en' => 'Dress Making Trade', 'course_fee' => '50.00', 'duration' => '360.00', 'overview' => NULL, 'overview_en' => NULL, 'target_group' => NULL, 'target_group_en' => NULL, 'objectives' => 'প্রশিক্ষণের মাধ্যমে আত্নকর্মসংস্থান সৃষ্টি করা', 'objectives_en' => 'Creating self-employment through training', 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => 'সরাসরি', 'training_methodology_en' => 'Directly', 'evaluation_system' => 'সরাসরি ব্যবহারিক ও তত্ত্বীয়', 'evaluation_system_en' => 'Directly practical and theoretical', 'prerequisite' => 'বাংলাদেশের নাগরিক ও বেকার', 'prerequisite_en' => NULL, 'eligibility' => 'অষ্টম শ্রেনী বা সমমান', 'eligibility_en' => 'Eight class or equivalent', 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/MJiX6IPY1bRrEjxAAIeRfV7lU6ujbo1647075780.jpg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[true,true],\\"freedom_fighter_info\\":[true,true],\\"disability_info\\":[true,true],\\"education_info\\":[true,true],\\"psc_passing_info\\":[false,false],\\"jsc_passing_info\\":[true,true],\\"ssc_passing_info\\":[false,false],\\"hsc_passing_info\\":[false,false],\\"diploma_passing_info\\":[false,false],\\"honors_passing_info\\":[false,false],\\"masters_passing_info\\":[false,false],\\"phd_passing_info\\":[false,false],\\"occupation_info\\":[true,true],\\"guardian_info\\":[true,true],\\"miscellaneous_info\\":[true,true]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-10 04:43:55', 'updated_at' => '2022-03-12 21:03:06', 'deleted_at' => NULL),
            array('id' => '50', 'code' => 'SSP00000001C0000003', 'institute_id' => '1', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'মৎস্য চাষ', 'title_en' => 'Fish culture training', 'course_fee' => '50.00', 'duration' => '360.00', 'overview' => NULL, 'overview_en' => NULL, 'target_group' => 'বেকার যুব ও যুব মহিলা,যাদের বয়স ১৮-৩৫ বছর, বাংলাদেশের স্থায়ী নাগরিক', 'target_group_en' => 'Unemployed youth and young women, aged 18-35, permanent citizens of Bangladesh', 'objectives' => 'প্রশিক্ষনের মাধ্যমে আত্নকর্মসংস্থান সৃস্টি করা', 'objectives_en' => 'Creating self-employment through training', 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => 'সরাসরি', 'training_methodology_en' => 'Directly', 'evaluation_system' => 'লিখিত ও মৌখিক পরীক্ষার মাধ্যমে', 'evaluation_system_en' => 'Through written and oral examinations', 'prerequisite' => 'বাংলাদেশের স্থায়ী নাগরিক', 'prerequisite_en' => 'Permanent citizen of Bangladesh', 'eligibility' => '৮ম শ্রেনী বা সমমানের', 'eligibility_en' => 'Class eight pass or equivalent', 'cover_image' => 'https://file-phase1.nise.gov.bd/uploads/iOga9MKRGCI2APlxLn8ILia4Tvznk41647074253.jpg', 'application_form_settings' => '"{\\"ethnic_group_info\\":[true,true],\\"freedom_fighter_info\\":[true,true],\\"disability_info\\":[false,false],\\"education_info\\":[true,true],\\"psc_passing_info\\":[false,false],\\"jsc_passing_info\\":[true,true],\\"ssc_passing_info\\":[false,false],\\"hsc_passing_info\\":[false,false],\\"diploma_passing_info\\":[false,false],\\"honors_passing_info\\":[false,false],\\"masters_passing_info\\":[false,false],\\"phd_passing_info\\":[false,false],\\"occupation_info\\":[false,false],\\"guardian_info\\":[true,true],\\"miscellaneous_info\\":[true,true]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-12 20:22:01', 'updated_at' => '2022-03-12 20:37:39', 'deleted_at' => NULL),
            array('id' => '51', 'code' => 'SSP00000001C0000004', 'institute_id' => '1', 'industry_association_id' => NULL, 'level' => '1', 'language_medium' => '1', 'branch_id' => NULL, 'program_id' => NULL, 'title' => 'ইলেকট্রিক্যাল এ্যান্ড হাউজওযারিং', 'title_en' => 'Electrical and Housewareing', 'course_fee' => '300.00', 'duration' => '360.00', 'overview' => 'প্রশিক্ষনের মাধ্যমে একজন প্রশিক্ষনার্থী ইলেকট্রিক ওয়ারিং,বিভিন্ন ইলেকট্রিক ফিটিংস সংযোজন,মোটর  ও ফ্যান সংযোজন  মেরামত ই্ত্যাদি বিষয়ে সম্মুখ ধারনা পাবে।', 'overview_en' => 'Through the training, a trainee will get first hand ideas on electric wiring, various electrical fittings, motor and fan connections, repairs etc.', 'target_group' => '১৮-৩৫ বছর বয়সি বেকার যুব ও যুব মহিলা', 'target_group_en' => 'Unemployed youth and young women aged 18-35', 'objectives' => 'প্রশিক্ষনের মাধ্যমে আত্নকর্মসংস্থানের সৃস্টি করা ও সরকারী বেসরকারী প্রতিষ্ঠানে চাকুরীর সুযোগ সৃস্টি করা', 'objectives_en' => 'Creating self-employment through training and creating job opportunities in government and non-government organizations', 'lessons' => NULL, 'lessons_en' => NULL, 'training_methodology' => 'সরাসরি ,তত্ত্বীয় ও ব্যবহারিক', 'training_methodology_en' => 'Direct, theoretical and practical', 'evaluation_system' => 'লিখিত ও ব্যবহারিক', 'evaluation_system_en' => 'Written and practical', 'prerequisite' => 'অবশ্যই বেকার ও বাংলাদেশের স্থায়ী নাগরিক হতে হবে।', 'prerequisite_en' => 'Must be unemployed and a permanent citizen of Bangladesh.', 'eligibility' => 'এস.এস.সি বা সমমানের পরীক্ষায় উত্তীর্ণ', 'eligibility_en' => 'Passed SSC or equivalent examination', 'cover_image' => NULL, 'application_form_settings' => '"{\\"ethnic_group_info\\":[true,true],\\"freedom_fighter_info\\":[true,true],\\"disability_info\\":[false,false],\\"education_info\\":[true,true],\\"psc_passing_info\\":[false,false],\\"jsc_passing_info\\":[true,true],\\"ssc_passing_info\\":[true,true],\\"hsc_passing_info\\":[false,false],\\"diploma_passing_info\\":[false,false],\\"honors_passing_info\\":[false,false],\\"masters_passing_info\\":[false,false],\\"phd_passing_info\\":[false,false],\\"occupation_info\\":[true,true],\\"guardian_info\\":[true,true],\\"miscellaneous_info\\":[true,false]}"', 'row_status' => '1', 'created_by' => NULL, 'updated_by' => NULL, 'created_at' => '2022-03-13 21:41:12', 'updated_at' => '2022-03-13 21:46:01', 'deleted_at' => NULL)
        ]);

        DB::table('course_skill')->truncate();
        DB::table('course_skill')->insert([
            array('course_id' => '4', 'skill_id' => '1'),
            array('course_id' => '1', 'skill_id' => '13'),
            array('course_id' => '6', 'skill_id' => '15'),
            array('course_id' => '8', 'skill_id' => '31'),
            array('course_id' => '10', 'skill_id' => '13'),
            array('course_id' => '12', 'skill_id' => '15'),
            array('course_id' => '15', 'skill_id' => '13'),
            array('course_id' => '18', 'skill_id' => '13'),
            array('course_id' => '19', 'skill_id' => '15'),
            array('course_id' => '21', 'skill_id' => '13'),
            array('course_id' => '24', 'skill_id' => '2'),
            array('course_id' => '27', 'skill_id' => '15'),
            array('course_id' => '29', 'skill_id' => '12'),
            array('course_id' => '30', 'skill_id' => '13'),
            array('course_id' => '31', 'skill_id' => '13'),
            array('course_id' => '32', 'skill_id' => '12'),
            array('course_id' => '35', 'skill_id' => '3'),
            array('course_id' => '38', 'skill_id' => '12'),
            array('course_id' => '41', 'skill_id' => '1'),
            array('course_id' => '42', 'skill_id' => '13'),
            array('course_id' => '43', 'skill_id' => '15'),
            array('course_id' => '44', 'skill_id' => '29'),
            array('course_id' => '47', 'skill_id' => '19'),
            array('course_id' => '50', 'skill_id' => '26'),
            array('course_id' => '51', 'skill_id' => '14')
        ]);

        Schema::enableForeignKeyConstraints();
    }

}
