# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Please do not change anything if you dont know what you are doing - Kalyan

variables:

  hostName: institute-dev.nise3.xyz

  # if values is false, then creating ingress will be escape
  enableEngress: true

  # app version, changing version will auto deploy the app to current version
  imageAppVersion: "1.0.23"

  # increase this when you need scale up
  replicaCount: 1

  imagePullPolicy: IfNotPresent

  serviceType: ClusterIP

  # service port, this provide traffic to ingress within this port
  servicePort: 80

  # target container port
  serviceTargetPort: 80

  #app buil image
  imageRepository: registry.nise3.xyz/nise3-institute-management-api-service

  #auto scaling config
  #autoScalingEnabled: 0

  #autoScalingMinReplicas: 1

  #autoScalingMaxReplicas: 100

  #autoScalingTargetCPUUtilizationPercentage: 80

  #autoScalingTargetMemoryUtilizationPercentage: 80


  # application config
  # APP_ENV environment available values are DEV/STAGING/PRODUCTION
  APP_ENV: "STAGING"

  DEV:
    APP_ENV: "local"
    APP_DEBUG: "false"
    APP_URL: "gateway-dev.nise3.xyz"
    DB_HOST: 192.168.10.95
    DB_PORT: "3306"
    DB_DATABASE: institute
    DB_USERNAME: n3_institute
    DB_PASSWORD: "nise*2022"
    RABBITMQ_HOST: "jaguar.rmq.cloudamqp.com"
    RABBITMQ_PORT: "5672"
    RABBITMQ_VHOST: "aeihxlmw"
    RABBITMQ_USER: "aeihxlmw"
    RABBITMQ_PASSWORD: "uC1-78rvplV09_2sVy5vEnLwG-iUdiWJ"

  STAGING:
    APP_ENV: "staging"
    APP_DEBUG: "false"
    APP_URL: "gateway-dev.nise3.xyz"
    DB_HOST: 172.17.177.79
    DB_PORT: "3306"
    DB_DATABASE: institute
    DB_USERNAME: n3_institute
    DB_PASSWORD: "kvx6V3Y^7"
    RABBITMQ_HOST: "jaguar.rmq.cloudamqp.com"
    RABBITMQ_PORT: "5672"
    RABBITMQ_VHOST: "aeihxlmw"
    RABBITMQ_USER: "aeihxlmw"
    RABBITMQ_PASSWORD: "uC1-78rvplV09_2sVy5vEnLwG-iUdiWJ"

  PRODUCTION:
    APP_ENV: "local"
    APP_DEBUG: "false"
    APP_URL: "gateway-dev.nise3.xyz"
    DB_HOST: 172.17.177.79
    DB_PORT: "3306"
    DB_DATABASE: institute
    DB_USERNAME: n3_institute
    DB_PASSWORD: "kvx6V3Y^7"
    RABBITMQ_HOST: "jaguar.rmq.cloudamqp.com"
    RABBITMQ_PORT: "5672"
    RABBITMQ_VHOST: "aeihxlmw"
    RABBITMQ_USER: "aeihxlmw"
    RABBITMQ_PASSWORD: "uC1-78rvplV09_2sVy5vEnLwG-iUdiWJ"

  #control git realese branch
  GIT_DEVELOPMENT_BRANCH: "develop"
  GIT_PRODUCTION_BRANCH: "master"
